// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Database › Deleting a patient removes their appointments (P1, #regression #database)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { check, pick, fake, field } from '../../support/helpers';
import { api } from '../../support/api';
import * as db from '../../support/db';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Database › Deleting a patient removes their appointments', () => {
  test(
    'Deleting a patient removes their appointments',
    { tag: ['@regression', '@database', '@p1'] },
    async ({ request }) => {
      const vars: Vars = {};
      // Block: API login as admin
      // Log in as admin
      const res1 = await api(request, {
        method: 'POST',
        url: '/api/auth/login',
        json: {
          email: env.adminEmail,
          password: secret('ADMIN_PASSWORD'),
        },
      });
      expect(res1.status, 'status').toBe(200);
      vars.admin = res1.body;
      // A patient name
      vars.patient = fake('name');
      // Create a patient
      const res2 = await api(request, {
        method: 'POST',
        url: '/api/patients',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
        json: {
          full_name: vars.patient,
          dob: '2001-07-07',
          phone: '+1-555-400-0000',
        },
      });
      expect(res2.status, 'status').toBe(201);
      vars.created = res2.body;
      // A free date
      vars.day = fake('date', { direction: 'future', days: 3000 });
      // Book an appointment for them
      const res3 = await api(request, {
        method: 'POST',
        url: '/api/appointments',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
        json: {
          patient_id: field(vars, 'created.id'),
          doctor_id: 3,
          date: vars.day,
          time: '15:00',
          reason: 'Follow-up',
        },
      });
      expect(res3.status, 'status').toBe(201);
      // Delete the patient
      const res4 = await api(request, {
        method: 'DELETE',
        url: `/api/patients/${field(vars, 'created.id')}`,
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
      });
      expect(res4.status, 'status').toBe(204);
      // No appointments are left for the deleted patient
      // SQL also in sql/deletingAPatientRemovesTheirAppointments/noAppointmentsAreLeftForTheDeletedPatient.sql
      const db1 = await db.query('clinic', 'SELECT COUNT(*) AS n FROM appointments WHERE patient_id = ?', [
        field(vars, 'created.id'),
      ]);
      check(pick(db1, 'value'), 'equals', 0, 'value equals');
    },
  );
});
