// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Database › Patient data is complete (P2, #database)
import { test, expect } from '@playwright/test';
import { check, pick } from '../../support/helpers';
import * as db from '../../support/db';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Database › Patient data is complete', () => {
  test('Patient data is complete', { tag: ['@database', '@p2'] }, async ({}) => {
    const vars: Vars = {};
    // Every patient has a code, a name and a date of birth
    // SQL also in sql/patientDataIsComplete/everyPatientHasACodeANameAndADateOfBirth.sql
    const db1 = await db.query('clinic', 'SELECT code, full_name, dob FROM patients');
    check(pick(db1, 'rowCount'), 'gte', 4, 'rowCount gte');
    check(pick(db1, 'column:code'), 'unique', null, 'column:code unique');
    check(pick(db1, 'column:full_name'), 'noNulls', null, 'column:full_name noNulls');
    check(pick(db1, 'column:dob'), 'noNulls', null, 'column:dob noNulls');
    // Doctor fees are positive
    // SQL also in sql/patientDataIsComplete/doctorFeesArePositive.sql
    const db2 = await db.query('clinic', 'SELECT fee FROM doctors');
    check(
      pick(db2, 'column:fee'),
      'inRange',
      {
        min: 1,
      },
      'column:fee inRange',
    );
  });
});
