// Generated by StepForge — by Md Zarin Tasnim
import 'dotenv/config';

/** Environment variables; defaults come from the exported environment. */
export const env: Record<string, string> & { baseUrl: string } = {
  baseUrl: process.env.BASE_URL ?? 'http://127.0.0.1:8101',
  adminEmail: process.env.ADMIN_EMAIL ?? 'admin@careclinic.test',
  receptionEmail: process.env.RECEPTION_EMAIL ?? 'reception@careclinic.test',
};

/** A secret from the environment (.env locally, CI secrets in pipelines). Never stored in the code. */
export function secret(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Set the ${name} environment variable (see .env.example)`);
  return value;
}
