// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Billing › Insured patients get 20% off (P1, #regression #api)
// Ana Lopez is insured (BlueCross); Dr. Dana Reyes charges 60.00, so the bill is 48.00.
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { check, pick, fake, field } from '../../support/helpers';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Billing › Insured patients get 20% off', () => {
  test('Insured patients get 20% off', { tag: ['@regression', '@api', '@p1'] }, async ({ request }) => {
    const vars: Vars = {};
    // Block: API login as admin
    // Log in as admin
    const res1 = await api(request, {
      method: 'POST',
      url: '/api/auth/login',
      json: {
        email: env.adminEmail,
        password: secret('ADMIN_PASSWORD'),
      },
    });
    expect(res1.status, 'status').toBe(200);
    vars.admin = res1.body;
    // A free date
    vars.day = fake('date', { direction: 'future', days: 3000 });
    // Book Ana Lopez with Dr. Reyes
    const res2 = await api(request, {
      method: 'POST',
      url: '/api/appointments',
      headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
      json: {
        patient_id: 1,
        doctor_id: 1,
        date: vars.day,
        time: '10:00',
        reason: 'Check-up',
      },
    });
    expect(res2.status, 'status').toBe(201);
    vars.appt = res2.body;
    // Get the bill
    const res3 = await api(request, {
      method: 'GET',
      url: `/api/appointments/${field(vars, 'appt.id')}/bill`,
      headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
    });
    expect(res3.status, 'status').toBe(200);
    check(pick(res3, '$.fee'), 'equals', 60, '$.fee equals');
    check(pick(res3, '$.discount'), 'equals', 12, '$.discount equals');
    check(pick(res3, '$.total'), 'equals', 48, '$.total equals');
  });
});
