# Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
# Scenario: Appointments › Book an appointment (P1, #smoke)

import pytest

from support.config import env, secret
from support.helpers import fake, text


@pytest.mark.smoke
@pytest.mark.p1
def test_book_an_appointment(browser):
    """Book an appointment"""
    vars = {}
    # Block: Sign in as the receptionist
    # Open the login page
    browser.goto("/login")
    # Email
    browser.fill(("label", "Email"), env["receptionEmail"])
    # Password
    browser.fill(("testId", "password"), secret("PASSWORD"))
    # Sign in
    browser.click(("role", "button", "Sign in"))
    # Open the booking form
    browser.goto("/appointments/new")
    # A free date
    vars["day"] = fake("date", direction="future", days=3000)
    # Patient
    browser.select(("label", "Patient"), label="Chloe Nguyen (PAT-1003)")
    # Doctor
    browser.select(("label", "Doctor"), label="Dr. Mei Lin · Pediatrics")
    # Date
    browser.fill(("testId", "appointment-date"), text(vars.get("day")))
    # Time
    browser.select(("label", "Time"), label="14:30")
    # Reason
    browser.fill(("label", "Reason for visit"), "Vaccination")
    # Book
    browser.click(("testId", "book-appointment"))
    # Booked
    browser.expect("text", ("role", "status"), expected="Appointment booked")
    # Listed
    browser.expect("textContains", ("css", "#appointments-table"), expected=text(vars.get("day")))
