import { expect, test, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import JSZip from 'jszip';

const shots = process.env.STEPFORGE_SHOTS;
const shot = async (page: Page, name: string) => {
  if (shots) await page.screenshot({ path: `${shots}/${name}.png`, fullPage: true });
};

async function sfApi<T>(page: Page, method: string, url: string, body?: unknown): Promise<T> {
  return page.evaluate(
    async ([m, u, b]) => {
      const res = await fetch(u as string, {
        method: m as string,
        headers: {
          'x-stepforge-token': (globalThis as unknown as { __STEPFORGE__: { token: string } }).__STEPFORGE__
            .token,
          'content-type': 'application/json',
        },
        body: b ? JSON.stringify(b) : undefined,
      });
      if (!res.ok) throw new Error(`${m} ${u} → ${res.status} ${await res.text()}`);
      return res.status === 204 ? null : res.json();
    },
    [method, url, body] as const,
  ) as Promise<T>;
}

test('exports: preview, page objects, download and history (Phase 12)', async ({ page }) => {
  test.setTimeout(90_000);
  await page.goto('/');
  const suite = JSON.parse(readFileSync('demo/clinic-app/stepforge/codegen-suite.json', 'utf8'));
  const imported = await sfApi<{ applicationId: string }>(
    page,
    'POST',
    '/api/applications/import?slug=careclinic-export',
    {
      ...suite,
      application: { ...suite.application, name: 'CareClinic Export' },
    },
  );
  await page.evaluate((id) => localStorage.setItem('stepforge.currentApp', id), imported.applicationId);

  await page.goto('/exports');
  await expect(page.getByLabel('Application', { exact: true })).toHaveValue(imported.applicationId);
  await page.getByRole('radio', { name: /Playwright Test/ }).click();
  await page.getByRole('button', { name: 'Preview' }).click();
  const files = page.getByTestId('export-files');
  await expect(files).toContainText('tests/patients/register-a-patient.spec.ts');
  await expect(files).toContainText('.github/workflows/stepforge-tests.yml');
  await expect(page.getByTestId('export-run')).toContainText('npx playwright test');
  await expect(page.getByTestId('export-warnings')).toContainText('the "clinic" connection is not set up');
  // A test file opens first; any file can be viewed (read-only).
  await expect(page.getByTestId('code-Generated file')).toContainText("from '@playwright/test'");
  await files.getByRole('button', { name: /register-a-patient\.spec\.ts/ }).click();
  // The editor renders only the lines in view: check one near the top.
  await expect(page.getByTestId('code-Generated file')).toContainText("getByLabel('Email', { exact: true })");
  await files.getByRole('button', { name: /\.env\.example/ }).click();
  await expect(page.getByTestId('code-Generated file')).toContainText('PASSWORD=');
  await shot(page, 'phase12-exports-preview');

  // Page objects.
  await page.getByRole('switch', { name: 'Page Object Model' }).click();
  await page.getByRole('button', { name: 'Preview' }).click();
  await expect(files).toContainText('pages/LoginPage.ts');

  // Download the project and look inside.
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.getByRole('button', { name: 'Download' }).click(),
  ]);
  expect(download.suggestedFilename()).toBe('careclinic-export-playwright-ts.zip');
  const zip = await JSZip.loadAsync(readFileSync((await download.path())!));
  expect(Object.keys(zip.files)).toContain('careclinic-export-playwright-ts/pages/HomePage.ts');
  expect(await zip.file('careclinic-export-playwright-ts/README.md')!.async('string')).toContain(
    'Generated by StepForge — by Md Zarin Tasnim',
  );
  await expect(page.getByTestId('export-history')).toContainText('careclinic-export-playwright-ts.zip');

  // Documentation target: Gherkin.
  await page.getByRole('radio', { name: /Gherkin features/ }).click();
  await page.getByRole('button', { name: 'Preview' }).click();
  await expect(files).toContainText('features/patients.feature');
  await files.getByRole('button', { name: /features\/patients\.feature/ }).click();
  await expect(page.getByTestId('code-Generated file')).toContainText('Scenario Outline: Register a patient');

  // From the Explorer: "Export code" preselects the scenario.
  await page.goto('/explorer');
  await page.getByRole('treeitem', { name: /Health and rejected logins/ }).click();
  await page.getByRole('link', { name: 'Export code' }).click();
  await expect(page).toHaveURL(/\/exports\?scenario=/);
  await expect(page.getByLabel('Tests to export')).toHaveValue('picked');
  await page.getByRole('radio', { name: /k6 script/ }).click();
  await page.getByRole('button', { name: 'Preview' }).click();
  // Only the chosen scenario is exported (the header counts them).
  await expect(page.getByTestId('code-Generated file')).toContainText('Functional checks of 1 API scenario');
  await shot(page, 'phase12-exports-k6');
});
