// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: End to end › Register in the UI, check the API and the database (P1, #smoke #api #database)
// One flow across three layers: the browser, the REST API and the database.
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { check, pick, fake, field } from '../../support/helpers';
import { api } from '../../support/api';
import * as db from '../../support/db';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('End to end › Register in the UI, check the API and the database', () => {
  test(
    'Register in the UI, check the API and the database',
    { tag: ['@smoke', '@api', '@database', '@p1'] },
    async ({ page, request }) => {
      const vars: Vars = {};
      // Block: Sign in as the receptionist
      // Open the login page
      await page.goto('/login');
      // Email
      await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
      // Password
      await page.getByTestId('password').fill(secret('PASSWORD'));
      // Sign in
      await page.getByRole('button', { name: 'Sign in', exact: true }).click();
      // Open the registration form
      await page.getByTestId('quick-new-patient').click();
      // A patient name
      vars.patient = fake('name');
      // Full name
      await page.getByLabel('Full name', { exact: true }).fill(String(vars.patient));
      // Date of birth
      await page.getByLabel('Date of birth', { exact: true }).fill('1984-08-21');
      // Phone
      await page.getByTestId('patient-phone').fill('+1-555-555-0199');
      // Save
      await page.getByTestId('save-patient').click();
      // Read the new patient code
      vars.code = ((await page.locator('#patient-code').textContent()) ?? '').trim();
      // Block: API login as admin
      // Log in as admin
      const res1 = await api(request, {
        method: 'POST',
        url: '/api/auth/login',
        json: {
          email: env.adminEmail,
          password: secret('ADMIN_PASSWORD'),
        },
      });
      expect(res1.status, 'status').toBe(200);
      vars.admin = res1.body;
      // Find the patient through the API
      const res2 = await api(request, {
        method: 'GET',
        url: '/api/patients',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
        params: { q: vars.code },
      });
      expect(res2.status, 'status').toBe(200);
      check(pick(res2, '$'), 'lengthEquals', 1, '$ lengthEquals');
      check(pick(res2, '$[0].full_name'), 'equals', vars.patient, '$[0].full_name equals');
      // The row is in the database
      // SQL also in sql/registerInTheUiCheckTheApiAndTheDatabase/theRowIsInTheDatabase.sql
      const db1 = await db.query('clinic', 'SELECT full_name, phone FROM patients WHERE code = ?', [
        vars.code,
      ]);
      check(pick(db1, 'rowCount'), 'equals', 1, 'rowCount equals');
      check(pick(db1, 'phone'), 'equals', '+1-555-555-0199', 'phone equals');
    },
  );
});
