// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: API › Appointments require a login (P1, #regression #api)
import { test, expect } from '@playwright/test';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('API › Appointments require a login', () => {
  test('Appointments require a login', { tag: ['@regression', '@api', '@p1'] }, async ({ request }) => {
    const vars: Vars = {};
    // List appointments without a token
    const res1 = await api(request, {
      method: 'GET',
      url: '/api/appointments',
    });
    expect(res1.status, 'status').toBe(401);
    // List patients without a token
    const res2 = await api(request, {
      method: 'GET',
      url: '/api/patients',
    });
    expect(res2.status, 'status').toBe(401);
  });
});
