// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: API › Deleting an unknown patient returns 404 (P3, #regression #api)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { field } from '../../support/helpers';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('API › Deleting an unknown patient returns 404', () => {
  test(
    'Deleting an unknown patient returns 404',
    { tag: ['@regression', '@api', '@p3'] },
    async ({ request }) => {
      const vars: Vars = {};
      // Block: API login as admin
      // Log in as admin
      const res1 = await api(request, {
        method: 'POST',
        url: '/api/auth/login',
        json: {
          email: env.adminEmail,
          password: secret('ADMIN_PASSWORD'),
        },
      });
      expect(res1.status, 'status').toBe(200);
      vars.admin = res1.body;
      // Delete a patient that does not exist
      const res2 = await api(request, {
        method: 'DELETE',
        url: '/api/patients/999999',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
      });
      expect(res2.status, 'status').toBe(404);
    },
  );
});
