// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: API › Doctors match the documented schema (P2, #regression #api)
// The OpenAPI document says a doctor's fee is a number.
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { check, pick, field } from '../../support/helpers';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('API › Doctors match the documented schema', () => {
  test(
    'Doctors match the documented schema',
    { tag: ['@regression', '@api', '@p2'] },
    async ({ request }) => {
      const vars: Vars = {};
      // Block: API login as admin
      // Log in as admin
      const res1 = await api(request, {
        method: 'POST',
        url: '/api/auth/login',
        json: {
          email: env.adminEmail,
          password: secret('ADMIN_PASSWORD'),
        },
      });
      expect(res1.status, 'status').toBe(200);
      vars.admin = res1.body;
      // TODO(StepForge): api.request: the JSON Schema check on "body" is not exported
      const res2 = await api(request, {
        method: 'GET',
        url: '/api/doctors',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
      });
      expect(res2.status, 'status').toBe(200);
      check(pick(res2, '$'), 'lengthEquals', 3, '$ lengthEquals');
    },
  );
});
