// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: API › Health check (P1, #smoke #api)
import { test, expect } from '@playwright/test';
import { check, pick } from '../../support/helpers';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('API › Health check', () => {
  test('Health check', { tag: ['@smoke', '@api', '@p1'] }, async ({ request }) => {
    const vars: Vars = {};
    // GET /api/health
    const res1 = await api(request, {
      method: 'GET',
      url: '/api/health',
    });
    expect(res1.status, 'status').toBe(200);
    check(pick(res1, '$.ok'), 'equals', true, '$.ok equals');
    check(pick(res1, 'time'), 'lt', 1000, 'time lt');
  });
});
