import { readFileSync } from 'node:fs';
import type { Plan, TestPlan } from './ir.ts';
import type { CiProvider, CodegenInput, CodegenScenario } from './types.ts';
import { envName, kebab } from './values.ts';

export const CREDIT = 'Generated by StepForge — by Md Zarin Tasnim';

/** A runtime helper shipped inside generated projects (packages/codegen/runtime/…). */
export const runtime = (path: string) => readFileSync(new URL(`../runtime/${path}`, import.meta.url), 'utf8');

/** The export date in local time (YYYY-MM-DD). */
export const day = (input: CodegenInput) => {
  const d = new Date(input.generatedAt);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};

/** Header lines (without comment markers) for a generated test file. */
export function headerLines(input: CodegenInput, s?: CodegenScenario): string[] {
  return [
    `${CREDIT} · ${input.application.name} · ${day(input)}`,
    ...(s
      ? [
          `Scenario: ${[...s.modulePath, s.name].join(' › ')} (${s.priority}${s.tags.length ? `, ${s.tags.map((t) => `#${t}`).join(' ')}` : ''})`,
          ...(s.description ? [s.description] : []),
          ...(s.preconditions ? [`Preconditions: ${s.preconditions}`] : []),
        ]
      : []),
  ];
}

export const dbEnv = (connection: string) =>
  `DB_${connection.replace(/[^A-Za-z0-9]+/g, '_').toUpperCase()}_URL`;

/** Environment variables the generated project reads, with defaults where they are not secret. */
export function envEntries(plan: Plan): { key: string; value: string; comment?: string }[] {
  const { input } = plan;
  const out: { key: string; value: string; comment?: string }[] = [
    { key: 'BASE_URL', value: input.environment.baseUrl, comment: `${input.environment.name} environment` },
  ];
  for (const v of plan.variables)
    out.push({ key: envName(v), value: input.environment.variables[v] ?? '', comment: `{{env.${v}}}` });
  for (const s of plan.secrets)
    out.push({ key: envName(s), value: '', comment: `secret {{secret.${s}}} — never commit its value` });
  const dbs = [
    ...new Set(
      plan.tests
        .flatMap((t) => t.ops.flatMap((o) => (o.op === 'db' ? [o] : [])))
        .map((o) => `${o.connection}|${o.engine}`),
    ),
  ];
  for (const d of dbs) {
    const [name, engine] = d.split('|') as [string, string];
    const example =
      engine === 'pg'
        ? 'postgres://user:password@localhost:5432/db'
        : engine === 'mysql'
          ? 'mysql://user:password@localhost:3306/db'
          : engine === 'sqlite'
            ? 'sqlite:./app.db'
            : 'postgres://…, mysql://… or sqlite:./app.db';
    out.push({
      key: dbEnv(name),
      value: '',
      comment: `"${name}" database${engine === 'any' ? '' : ` (${engine})`}, e.g. ${example}`,
    });
  }
  if (plan.tests.some((t) => t.usesEmail))
    out.push({ key: 'MAILPIT_URL', value: 'http://127.0.0.1:8025', comment: 'Mailpit web/API address' });
  return out;
}

export function envExample(plan: Plan): string {
  return [
    `# ${CREDIT}`,
    '# Copy to .env and fill in. Secrets are never exported by StepForge.',
    ...envEntries(plan).flatMap((e) => [...(e.comment ? [`# ${e.comment}`] : []), `${e.key}=${e.value}`]),
    '',
  ].join('\n');
}

/** Test file path: tests/<module path>/<scenario>. */
export function testPath(
  t: TestPlan,
  ext: (base: string) => string,
  dir = 'tests',
  sep: (s: string) => string = kebab,
): string {
  const folders = t.scenario.modulePath.map((m) => sep(m));
  return [dir, ...folders, ext(sep(t.scenario.name))].join('/');
}

export function warningList(plan: Plan): string[] {
  return plan.warnings.map(
    (w) => `- ${w.scenario ? `**${w.scenario}**` : ''}${w.step ? ` — ${w.step}` : ''}: ${w.message}`,
  );
}

export function readme(
  plan: Plan,
  o: { title: string; install: string[]; run: string[]; notes?: string[]; layout: string[] },
): string {
  const { input } = plan;
  const env = envEntries(plan);
  return [
    `# ${input.application.name} — ${o.title}`,
    '',
    `_${CREDIT} on ${day(input)} from the **${input.environment.name}** environment._`,
    '',
    `${plan.tests.length} scenario${plan.tests.length === 1 ? '' : 's'}: ${plan.tests.map((t) => t.scenario.name).join(', ')}.`,
    '',
    '## Setup',
    '',
    '```bash',
    ...o.install,
    'cp .env.example .env   # then fill in the values',
    '```',
    '',
    '## Run',
    '',
    '```bash',
    ...o.run,
    '```',
    '',
    '## Configuration',
    '',
    '| Variable | Meaning |',
    '|---|---|',
    ...env.map((e) => `| \`${e.key}\` | ${e.comment ?? ''}${e.value ? ` (default \`${e.value}\`)` : ''} |`),
    '',
    'Secret values are not part of the export: set them in `.env` locally and as CI secrets in pipelines.',
    '',
    '## Layout',
    '',
    ...o.layout.map((l) => `- ${l}`),
    ...(o.notes?.length ? ['', '## Notes', '', ...o.notes.map((n) => `- ${n}`)] : []),
    ...(plan.warnings.length
      ? [
          '',
          '## Needs attention',
          '',
          'These steps could not be translated exactly; the code has a `TODO(StepForge)` comment where each one was:',
          '',
          ...warningList(plan),
        ]
      : []),
    '',
  ].join('\n');
}

type Family = 'node-playwright' | 'node-cypress' | 'python' | 'python-playwright' | 'java' | 'k6';

const SETUP: Record<Family, { github: string[]; gitlabImage: string; gitlab: string[] }> = {
  'node-playwright': {
    github: [
      '      - uses: actions/setup-node@v4',
      '        with:',
      '          node-version: 22',
      '      - run: npm install',
      '      - run: npx playwright install --with-deps chromium',
      '      - run: npx playwright test',
    ],
    gitlabImage: 'mcr.microsoft.com/playwright:v1.63.0-noble',
    gitlab: ['npm install', 'npx playwright test'],
  },
  'node-cypress': {
    github: [
      '      - uses: actions/setup-node@v4',
      '        with:',
      '          node-version: 22',
      '      - run: npm install',
      '      - run: npx cypress run',
    ],
    gitlabImage: 'cypress/browsers:latest',
    gitlab: ['npm install', 'npx cypress run'],
  },
  python: {
    github: [
      '      - uses: actions/setup-python@v5',
      '        with:',
      "          python-version: '3.12'",
      '      - run: pip install -r requirements.txt',
      '      - run: pytest',
    ],
    gitlabImage: 'python:3.12',
    gitlab: ['pip install -r requirements.txt', 'pytest'],
  },
  'python-playwright': {
    github: [
      '      - uses: actions/setup-python@v5',
      '        with:',
      "          python-version: '3.12'",
      '      - run: pip install -r requirements.txt',
      '      - run: python -m playwright install --with-deps chromium',
      '      - run: pytest',
    ],
    gitlabImage: 'mcr.microsoft.com/playwright/python:v1.63.0-noble',
    gitlab: ['pip install -r requirements.txt', 'pytest'],
  },
  java: {
    github: [
      '      - uses: actions/setup-java@v4',
      '        with:',
      '          distribution: temurin',
      "          java-version: '17'",
      '      - run: mvn -B test',
    ],
    gitlabImage: 'maven:3-eclipse-temurin-17',
    gitlab: ['mvn -B test'],
  },
  k6: {
    github: ['      - uses: grafana/setup-k6-action@v1', '      - run: k6 run script.js'],
    gitlabImage: 'grafana/k6:latest',
    gitlab: ['k6 run script.js'],
  },
};

/** GitHub Actions and/or GitLab CI files; secrets come from the CI's secret store. */
export function ciFiles(plan: Plan, family: Family, providers: CiProvider[] = []): Record<string, string> {
  const env = envEntries(plan);
  const isSecret = (k: string) => plan.secrets.some((s) => envName(s) === k) || k.startsWith('DB_');
  const out: Record<string, string> = {};
  if (providers.includes('github'))
    out['.github/workflows/stepforge-tests.yml'] = [
      `# ${CREDIT}`,
      `name: ${plan.input.application.name} tests`,
      'on:',
      '  push:',
      '  workflow_dispatch:',
      'jobs:',
      '  tests:',
      '    runs-on: ubuntu-latest',
      '    env:',
      ...env.map((e) =>
        isSecret(e.key)
          ? `      ${e.key}: \${{ secrets.${e.key} }}`
          : `      ${e.key}: \${{ vars.${e.key} || '${e.value.replace(/'/g, "''")}' }}`,
      ),
      '    steps:',
      '      - uses: actions/checkout@v4',
      ...SETUP[family].github,
      '',
    ].join('\n');
  if (providers.includes('gitlab'))
    out['.gitlab-ci.yml'] = [
      `# ${CREDIT}`,
      '# Set the secret variables (masked) in Settings → CI/CD → Variables.',
      'tests:',
      `  image: ${SETUP[family].gitlabImage}`,
      '  variables:',
      ...env.filter((e) => !isSecret(e.key)).map((e) => `    ${e.key}: "${e.value.replace(/"/g, '\\"')}"`),
      '  script:',
      ...SETUP[family].gitlab.map((c) => `    - ${c}`),
      '',
    ].join('\n');
  return out;
}

/** Test-case rows (or a single row without data). */
export const casesOf = (s: CodegenScenario) =>
  s.testCases.length ? s.testCases : [{ code: '', title: '', data: {} as Record<string, unknown> }];
