// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Performance › The doctors' schedule answers quickly (P3, #api #performance)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { check, pick, field } from '../../support/helpers';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe("Performance › The doctors' schedule answers quickly", () => {
  test(
    "The doctors' schedule answers quickly",
    { tag: ['@api', '@performance', '@p3'] },
    async ({ request }) => {
      const vars: Vars = {};
      // Block: API login as admin
      // Log in as admin
      const res1 = await api(request, {
        method: 'POST',
        url: '/api/auth/login',
        json: {
          email: env.adminEmail,
          password: secret('ADMIN_PASSWORD'),
        },
      });
      expect(res1.status, 'status').toBe(200);
      vars.admin = res1.body;
      // Doctors' schedule
      const res2 = await api(request, {
        method: 'GET',
        url: '/api/doctors/schedule',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
      });
      expect(res2.status, 'status').toBe(200);
      check(pick(res2, 'time'), 'lt', 150, 'time lt');
    },
  );
});
