// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Performance › The dashboard loads quickly (P2, #performance)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Performance › The dashboard loads quickly', () => {
  test('The dashboard loads quickly', { tag: ['@performance', '@p2'] }, async ({ page }) => {
    const vars: Vars = {};
    // Block: Sign in as the receptionist
    // Open the login page
    await page.goto('/login');
    // Email
    await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
    // Password
    await page.getByTestId('password').fill(secret('PASSWORD'));
    // Sign in
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    // TODO(StepForge): perf.pageMetrics: performance measurements run only in StepForge
  });
});
