// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Email › Sign up with email verification (P1, #smoke #email)
import { test, expect } from '@playwright/test';
import { containing, runId } from '../../support/helpers';
import * as mail from '../../support/mail';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Email › Sign up with email verification', () => {
  test('Sign up with email verification', { tag: ['@smoke', '@email', '@p1'] }, async ({ page }) => {
    const testStart = new Date();
    const vars: Vars = {};
    // A unique address for this run
    vars.email = `qa+${runId}@example.test`;
    // Open the sign-up page
    await page.goto('/signup');
    // Full name
    await page.getByLabel('Full name', { exact: true }).fill('Quinn QA');
    // Email
    await page.getByTestId('signup-email').fill(String(vars.email));
    // Password
    await page.getByLabel('Password', { exact: true }).fill('Quinn-QA-2026');
    // Create the account
    await page.getByTestId('signup-submit').click();
    // Wait for the verification email
    const email1 = await mail.waitForEmail({
      to: String(vars.email),
      subject: 'Verify your CareClinic account',
      since: testStart,
      timeoutMs: 20000,
    });
    // It has a code and a link
    mail.assertEmail(email1, { bodyContains: 'verification code', hasLink: true });
    // Read the code
    vars.otp = mail.otp(email1);
    // Enter the code
    await page.getByTestId('verify-code').fill(String(vars.otp));
    // Verify
    await page.getByRole('button', { name: 'Verify email', exact: true }).click();
    // Verified
    await expect(page).toHaveURL(containing('verified=1'));
  });
});
