// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Email › Verify with the link in the email (P2, #regression #email)
import { test, expect } from '@playwright/test';
import { containing, runId } from '../../support/helpers';
import * as mail from '../../support/mail';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Email › Verify with the link in the email', () => {
  test('Verify with the link in the email', { tag: ['@regression', '@email', '@p2'] }, async ({ page }) => {
    const testStart = new Date();
    const vars: Vars = {};
    // A unique address for this run
    vars.email = `qa.link+${runId}@example.test`;
    // Open the sign-up page
    await page.goto('/signup');
    // Full name
    await page.getByLabel('Full name', { exact: true }).fill('Lee Link');
    // Email
    await page.getByTestId('signup-email').fill(String(vars.email));
    // Password
    await page.getByLabel('Password', { exact: true }).fill('Lee-Link-2026');
    // Create the account
    await page.getByTestId('signup-submit').click();
    // Wait for the verification email
    const email1 = await mail.waitForEmail({
      to: String(vars.email),
      subject: 'Verify your CareClinic account',
      since: testStart,
      timeoutMs: 20000,
    });
    // Open the link in the email
    await page.goto(mail.link(email1, { contains: 'code=' }));
    // Verified
    await expect(page).toHaveURL(containing('verified=1'));
  });
});
