// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Sign in › A wrong password is refused (P2, #regression)
import { test, expect } from '@playwright/test';
import { containing } from '../../support/helpers';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

const testCases: { code: string; title: string; data: Vars }[] = [
  {
    code: 'TC-SIG-001',
    title: 'Wrong password',
    data: { email: 'reception@careclinic.test', password: 'not-the-password' },
  },
  {
    code: 'TC-SIG-002',
    title: 'Unknown user',
    data: { email: 'nobody@careclinic.test', password: 'Reception123!' },
  },
];

test.describe('Sign in › A wrong password is refused', () => {
  for (const { code, title, data } of testCases) {
    test(`${code} ${title}`, { tag: ['@regression', '@p2'] }, async ({ page }) => {
      const vars: Vars = {};
      // Open the login page
      await page.goto('/login');
      // Email
      await page.getByLabel('Email', { exact: true }).fill(String(data.email));
      // Wrong password
      await page.getByTestId('password').fill(String(data.password));
      // Sign in
      await page.getByRole('button', { name: 'Sign in', exact: true }).click();
      // An error is shown
      await expect(page.getByTestId('login-error')).toHaveText('Invalid email or password');
      // Still on the login page
      await expect(page).toHaveURL(containing('/login'));
    });
  }
});
