// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Sign in › Sign in with valid credentials (P1, #smoke)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Sign in › Sign in with valid credentials', () => {
  test('Sign in with valid credentials', { tag: ['@smoke', '@p1'] }, async ({ page }) => {
    const vars: Vars = {};
    // Block: Sign in as the receptionist
    // Open the login page
    await page.goto('/login');
    // Email
    await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
    // Password
    await page.getByTestId('password').fill(secret('PASSWORD'));
    // Sign in
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    // The dashboard greets the user
    await expect(page.getByRole('heading', { name: 'Welcome, Riley Reception', exact: true })).toContainText(
      'Welcome, Riley Reception',
    );
    // Patients are counted
    await expect(page.getByTestId('kpi-patients')).toBeVisible();
  });
});
