// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Patients › Register a patient (P1, #smoke)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { fake } from '../../support/helpers';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Patients › Register a patient', () => {
  test('Register a patient', { tag: ['@smoke', '@p1'] }, async ({ page }) => {
    const vars: Vars = {};
    // Block: Sign in as the receptionist
    // Open the login page
    await page.goto('/login');
    // Email
    await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
    // Password
    await page.getByTestId('password').fill(secret('PASSWORD'));
    // Sign in
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    // Open the registration form
    await page.getByTestId('quick-new-patient').click();
    // A patient name
    vars.patient = fake('name');
    // Full name
    await page.getByLabel('Full name', { exact: true }).fill(String(vars.patient));
    // Date of birth
    await page.getByLabel('Date of birth', { exact: true }).fill('1990-05-17');
    // Phone
    await page.getByTestId('patient-phone').fill('+1-555-777-1234');
    // Insurance
    await page.getByLabel('Insurance provider', { exact: true }).fill('BlueCross');
    // Save
    await page.getByTestId('save-patient').click();
    // Patient saved
    await expect(page.getByRole('status')).toHaveText(new RegExp('Patient PAT-\\d+ registered'));
    // The patient page shows the name
    await expect(page.getByTestId('patient-title')).toHaveText(String(vars.patient));
    // Insurance is kept
    await expect(page.getByTestId('patient-insurance-value')).toHaveText('BlueCross');
  });
});
