// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Patients › Search patients (P2, #regression)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

const testCases: { code: string; title: string; data: Vars }[] = [
  { code: 'TC-PAT-101', title: 'By name', data: { query: 'Ana', expected: 'Ana Lopez' } },
  { code: 'TC-PAT-102', title: 'By patient code', data: { query: 'PAT-1002', expected: 'Ben Carter' } },
  { code: 'TC-PAT-103', title: 'By phone', data: { query: '201-0004', expected: 'David Okafor' } },
];

test.describe('Patients › Search patients', () => {
  for (const { code, title, data } of testCases) {
    test(`${code} ${title}`, { tag: ['@regression', '@p2'] }, async ({ page }) => {
      const vars: Vars = {};
      // Block: Sign in as the receptionist
      // Open the login page
      await page.goto('/login');
      // Email
      await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
      // Password
      await page.getByTestId('password').fill(secret('PASSWORD'));
      // Sign in
      await page.getByRole('button', { name: 'Sign in', exact: true }).click();
      // Open the patient list
      await page.goto('/patients');
      // Search
      await page.getByTestId('patient-search').fill(String(data.query));
      // Search
      await page.getByTestId('patient-search').press('Enter');
      // The patient is listed
      await expect(page.getByTestId('patients-table')).toContainText(String(data.expected));
    });
  }
});
