// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Patients › The same patient cannot be registered twice (P1, #regression #api)
// The API documents 409 Conflict for a duplicate patient (same name and date of birth).
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { fake, field } from '../../support/helpers';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Patients › The same patient cannot be registered twice', () => {
  test(
    'The same patient cannot be registered twice',
    { tag: ['@regression', '@api', '@p1'] },
    async ({ request }) => {
      const vars: Vars = {};
      // Block: API login as admin
      // Log in as admin
      const res1 = await api(request, {
        method: 'POST',
        url: '/api/auth/login',
        json: {
          email: env.adminEmail,
          password: secret('ADMIN_PASSWORD'),
        },
      });
      expect(res1.status, 'status').toBe(200);
      vars.admin = res1.body;
      // A patient name
      vars.patient = fake('name');
      // Register the patient
      const res2 = await api(request, {
        method: 'POST',
        url: '/api/patients',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
        json: {
          full_name: vars.patient,
          dob: '1979-03-14',
          phone: '+1-555-300-0000',
        },
      });
      expect(res2.status, 'status').toBe(201);
      // Register the same patient again
      const res3 = await api(request, {
        method: 'POST',
        url: '/api/patients',
        headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
        json: {
          full_name: vars.patient,
          dob: '1979-03-14',
          phone: '+1-555-300-0000',
        },
      });
      expect(res3.status, 'status').toBe(409);
    },
  );
});
