// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Dashboard › Dashboard labels the appointment count (P3, #regression)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Dashboard › Dashboard labels the appointment count', () => {
  test('Dashboard labels the appointment count', { tag: ['@regression', '@p3'] }, async ({ page }) => {
    const vars: Vars = {};
    // Block: Sign in as the receptionist
    // Open the login page
    await page.goto('/login');
    // Email
    await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
    // Password
    await page.getByTestId('password').fill(secret('PASSWORD'));
    // Sign in
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    // The KPI is labelled correctly
    await expect(page.getByTestId('kpi-appointments-label')).toHaveText('Upcoming appointments');
  });
});
