// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Appointments › A doctor cannot be double-booked (P1, #regression #api)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { check, pick, fake, field } from '../../support/helpers';
import { api } from '../../support/api';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Appointments › A doctor cannot be double-booked', () => {
  test('A doctor cannot be double-booked', { tag: ['@regression', '@api', '@p1'] }, async ({ request }) => {
    const vars: Vars = {};
    // Block: API login as admin
    // Log in as admin
    const res1 = await api(request, {
      method: 'POST',
      url: '/api/auth/login',
      json: {
        email: env.adminEmail,
        password: secret('ADMIN_PASSWORD'),
      },
    });
    expect(res1.status, 'status').toBe(200);
    vars.admin = res1.body;
    // A free date
    vars.day = fake('date', { direction: 'future', days: 3000 });
    // Book a slot
    const res2 = await api(request, {
      method: 'POST',
      url: '/api/appointments',
      headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
      json: {
        patient_id: 1,
        doctor_id: 2,
        date: vars.day,
        time: '09:30',
        reason: 'Check-up',
      },
    });
    expect(res2.status, 'status').toBe(201);
    check(pick(res2, '$.status'), 'equals', 'booked', '$.status equals');
    // Book the same slot for another patient
    const res3 = await api(request, {
      method: 'POST',
      url: '/api/appointments',
      headers: { Authorization: `Bearer ${String(field(vars, 'admin.token'))}` },
      json: {
        patient_id: 2,
        doctor_id: 2,
        date: vars.day,
        time: '09:30',
        reason: 'Check-up',
      },
    });
    expect(res3.status, 'status').toBe(409);
    check(pick(res3, '$.message'), 'contains', 'already booked', '$.message contains');
  });
});
