// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Appointments › Book an appointment (P1, #smoke)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { fake } from '../../support/helpers';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Appointments › Book an appointment', () => {
  test('Book an appointment', { tag: ['@smoke', '@p1'] }, async ({ page }) => {
    const vars: Vars = {};
    // Block: Sign in as the receptionist
    // Open the login page
    await page.goto('/login');
    // Email
    await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
    // Password
    await page.getByTestId('password').fill(secret('PASSWORD'));
    // Sign in
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    // Open the booking form
    await page.goto('/appointments/new');
    // A free date
    vars.day = fake('date', { direction: 'future', days: 3000 });
    // Patient
    await page.getByLabel('Patient', { exact: true }).selectOption({ label: 'Chloe Nguyen (PAT-1003)' });
    // Doctor
    await page.getByLabel('Doctor', { exact: true }).selectOption({ label: 'Dr. Mei Lin · Pediatrics' });
    // Date
    await page.getByTestId('appointment-date').fill(String(vars.day));
    // Time
    await page.getByLabel('Time', { exact: true }).selectOption({ label: '14:30' });
    // Reason
    await page.getByLabel('Reason for visit', { exact: true }).fill('Vaccination');
    // Book
    await page.getByTestId('book-appointment').click();
    // Booked
    await expect(page.getByRole('status')).toHaveText('Appointment booked');
    // Listed
    await expect(page.locator('#appointments-table')).toContainText(String(vars.day));
  });
});
