// Generated by StepForge — by Md Zarin Tasnim · CareClinic · 2026-10-07
// Scenario: Appointments › The booking form refuses a double booking (P1, #regression)
import { test, expect } from '@playwright/test';
import { env, secret } from '../../support/config';
import { fake } from '../../support/helpers';

type Vars = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

test.describe('Appointments › The booking form refuses a double booking', () => {
  test('The booking form refuses a double booking', { tag: ['@regression', '@p1'] }, async ({ page }) => {
    const vars: Vars = {};
    // Block: Sign in as the receptionist
    // Open the login page
    await page.goto('/login');
    // Email
    await page.getByLabel('Email', { exact: true }).fill(env.receptionEmail);
    // Password
    await page.getByTestId('password').fill(secret('PASSWORD'));
    // Sign in
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    // A free date
    vars.day = fake('date', { direction: 'future', days: 3000 });
    // Open the booking form
    await page.goto('/appointments/new');
    // Patient
    await page.getByLabel('Patient', { exact: true }).selectOption({ label: 'Ana Lopez (PAT-1001)' });
    // Doctor
    await page.getByLabel('Doctor', { exact: true }).selectOption({ label: 'Dr. Omar Haddad · Cardiology' });
    // Date
    await page.getByTestId('appointment-date').fill(String(vars.day));
    // Time
    await page.getByLabel('Time', { exact: true }).selectOption({ label: '11:00' });
    // Book
    await page.getByTestId('book-appointment').click();
    // First booking accepted
    await expect(page.getByRole('status')).toHaveText('Appointment booked');
    // Open the booking form
    await page.goto('/appointments/new');
    // Patient
    await page.getByLabel('Patient', { exact: true }).selectOption({ label: 'Ben Carter (PAT-1002)' });
    // Doctor
    await page.getByLabel('Doctor', { exact: true }).selectOption({ label: 'Dr. Omar Haddad · Cardiology' });
    // Date
    await page.getByTestId('appointment-date').fill(String(vars.day));
    // Time
    await page.getByLabel('Time', { exact: true }).selectOption({ label: '11:00' });
    // Book
    await page.getByTestId('book-appointment').click();
    // The second booking is refused
    await expect(page.getByTestId('booking-error')).toContainText('already booked');
  });
});
